// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxFOM3CoVqEWx-IX_uXzsCEJFt2E4R7E',
    appId: '1:534678766338:web:bd891f1b730c42d9f1781b',
    messagingSenderId: '534678766338',
    projectId: 'randommeal108',
    authDomain: 'randommeal108.firebaseapp.com',
    storageBucket: 'randommeal108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ttsDLXfPW3knXjFchtm3w1z5PcwB2sU',
    appId: '1:534678766338:android:a93192ec72c93483f1781b',
    messagingSenderId: '534678766338',
    projectId: 'randommeal108',
    storageBucket: 'randommeal108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5SuNEIzCMob0b_bHu5TloKsw1orojF0',
    appId: '1:534678766338:ios:2ee92795b89955f1f1781b',
    messagingSenderId: '534678766338',
    projectId: 'randommeal108',
    storageBucket: 'randommeal108.firebasestorage.app',
    iosBundleId: 'com.example.randommeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5SuNEIzCMob0b_bHu5TloKsw1orojF0',
    appId: '1:534678766338:ios:2ee92795b89955f1f1781b',
    messagingSenderId: '534678766338',
    projectId: 'randommeal108',
    storageBucket: 'randommeal108.firebasestorage.app',
    iosBundleId: 'com.example.randommeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlxFOM3CoVqEWx-IX_uXzsCEJFt2E4R7E',
    appId: '1:534678766338:web:650de6f72d219897f1781b',
    messagingSenderId: '534678766338',
    projectId: 'randommeal108',
    authDomain: 'randommeal108.firebaseapp.com',
    storageBucket: 'randommeal108.firebasestorage.app',
  );

}